style: none
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://git.aleyoscar.com/emet/emet-finances
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - docs
        - refactor
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      docs: Documentation
      refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
